version: "3.7"
services:
  db:
    image: postgres:14.4
    container_name: test-app-db
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "secret"
      PGDATA: /var/lib/pg_data
    ports:
      - "5432:5432"
    volumes:
      - ./storage/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 0.5G
  go:
    container_name: test-app-go
    build:
        context: ./app
        dockerfile: ./../docker/go/Dockerfile
    env_file: .env
    depends_on:
      - db
    networks:
      - default
    ports:
    - "8080:8080"